session_name: dev

windows:
  - window_name: btop
    panes:
    - shell_command:
      - btop
  - window_name: build/test
    layout: even-vertical
    panes:
    - pane
    - pane
  - window_name: shell
    panes:
    - pane
  - window_name: nvim
    panes:
    - shell_command:
      - nvim
